// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5186' | (string & {});
};

export type CtChuyenKhoRequest = {
    maLo: string;
    soLuongChuyen: number;
    ghiChu?: string | null;
};

export type CtChuyenKhoResponse = {
    maCTCK?: string;
    maLo?: string;
    maLoCode?: string | null;
    tenSanPham?: string | null;
    loaiSanPham?: string | null;
    donViCoSo?: string | null;
    soLuongChuyen?: number;
    donGia?: number | null;
    hanSuDung?: string | null;
    ghiChu?: string | null;
    trangThai?: string | null;
};

export type CtPhieuNhapRequest = {
    maSP?: string;
    ngaySanXuat?: string | null;
    hanSuDung?: string;
    soLuong?: number;
    donGia?: number | null;
    donViNhap?: string | null;
};

export type CtPhieuNhapResponse = {
    maCTPN?: string;
    maPN?: string;
    maLo?: string;
    maLoCode?: string | null;
    tenSP?: string | null;
    ngaySanXuat?: string | null;
    hanSuDung?: string | null;
    soLuong?: number;
    donGia?: number | null;
    donViNhap?: string | null;
    soLuongQuyDoi?: number;
    donGiaCoSo?: number;
    readonly thanhTien?: number;
};

export type CtPhieuNhapUpdateRequest = {
    maCTPN?: string;
    maSP?: string | null;
    soLuong?: number;
    donGia?: number | null;
    donViNhap?: string | null;
    ngaySanXuat?: string | null;
    hanSuDung?: string | null;
};

export type CheckAllKhoRequest = {
    maLo: string;
    soLuongCan: number;
};

export type CheckReturnableRequest = {
    maPB: string;
    maLo: string;
    soLuong?: number;
};

export type CheckTonKhoRequest = {
    maKhoXuat: string;
    maLo: string;
    soLuongChuyen: number;
};

export type ChiTietChuyenKhoUpdateItem = {
    maCTCK?: string | null;
    maLo: string;
    soLuongChuyen: number;
    ghiChu?: string | null;
    trangThai: TrangThaiPhieuChuyenKhoChiTietEnum;
    isDeleted?: boolean;
};

export type ChiTietPhieuBanRequest = {
    maLo: string;
    soLuong: number;
    donGia: number;
    ghiChu?: string | null;
};

export type ChiTietPhieuBanResponse = {
    maCTPB?: string;
    maLo?: string;
    maLoCode?: string | null;
    tenSanPham?: string | null;
    donViCoSo?: string | null;
    soLuong?: number;
    donViBan?: string | null;
    donGia?: number;
    soLuongQuyDoi?: number;
    giaVonCoSo?: number;
    thanhTienVon?: number;
    hanSuDung?: string | null;
    ghiChu?: string | null;
};

export type ChiTietPhieuChuyenKhoResponse = {
    maCK?: string;
    maCKCode?: string | null;
    ngayLap?: string;
    tenKhoXuat?: string | null;
    tenKhoNhan?: string | null;
    ghiChu?: string | null;
    maKhoXuat?: string;
    maKhoNhan?: string;
    danhSachSanPham?: Array<CtChuyenKhoResponse> | null;
};

export type ChiTietPhieuTraDetailResponse = {
    maCTPT?: string;
    maLo?: string;
    maLoCode?: string | null;
    tenSanPham?: string | null;
    donViCoSo?: string | null;
    donViTra?: string | null;
    soLuongTra?: number;
    donGiaHoan?: number;
    thanhTienTra?: number;
    hanSuDung?: string | null;
    ghiChu?: string | null;
};

export type ChiTietPhieuTraRequest = {
    maLo: string;
    soLuong?: number;
    ghiChu?: string | null;
};

export type CongNoHistoryResponse = {
    ngay?: string;
    loaiPhieu?: string | null;
    maPhieu?: string | null;
    ghiChu?: string | null;
    phatSinhNo?: number;
    daThanhToan?: number;
    soDuSau?: number;
};

export type CongNoTongHopResponse = {
    maDoiTuong?: string;
    maDoiTuongCode?: string | null;
    tenDoiTuong?: string | null;
    loaiDoiTuong?: string | null;
    tongPhatSinh?: number;
    daThanhToan?: number;
    duNo?: number;
    coQuaHan?: boolean;
    hanThanhToanGanNhat?: string | null;
};

export type CreateCongNoRequest = {
    maDoiTuong: string;
    soTien: number;
    ngayPhatSinh: string;
    maPhieuCode?: string | null;
    hanThanhToan?: string | null;
    ghiChu?: string | null;
};

export type CreateKhoHangRequest = {
    tenKho: string;
    diaChi: string;
    trangThai: TrangThaiKhoEnum;
    ghiChu?: string | null;
};

export type CreatePhieuBanRequest = {
    maKH: string;
    ngayBan: string;
    chietKhauPhanTram?: number;
    hinhThucThanhToan: HinhThucThanhToanEnum;
    tienCoc?: number;
    hanTra?: string | null;
    ghiChu?: string | null;
    danhSachChiTiet: Array<ChiTietPhieuBanRequest>;
};

export type CreatePhieuTraRequest = {
    maPB: string;
    hinhThucHoanTien: HinhThucHoanTienEnum;
    lyDoTra?: string | null;
    danhSachChiTiet?: Array<ChiTietPhieuTraRequest> | null;
};

export type CreateTaiKhoanRequest = {
    hoTen: string;
    email: string;
    password: string;
};

export type DonViQuyDoiItem = {
    donViNhap?: string | null;
    tyLe?: number;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type GiaBanCreateRequest = {
    maSP: string;
    donGiaBan?: number;
    tuNgay: string;
    denNgay?: string | null;
    ghiChu?: string | null;
};

export type GiaBanUpdateRequest = {
    donGiaBan?: number;
    tuNgay: string;
    denNgay?: string | null;
    ghiChu?: string | null;
};

export type HinhThucHoanTienEnum = 0 | 1;

export type HinhThucThanhToanEnum = 0 | 1 | 2;

export type KhachHangCreateRequest = {
    tenKH: string;
    soDienThoai?: string | null;
    diaChi?: string | null;
    loaiKhachHang: LoaiKhachHangEnum;
    hanMucCongNo?: number | null;
    trangThai: TrangThaiKhachHangEnum;
    ghiChu?: string | null;
};

export type KhachHangPhieuBanResponse = {
    maKH?: string;
    maKHCode?: string | null;
    tenKH?: string | null;
    soDienThoai?: string | null;
    diaChi?: string | null;
    loaiKhachHang?: string | null;
    tongMua?: number;
    congNoHienTai?: number;
    hanMucCongNo?: number | null;
    danhSachPhieuBan?: Array<PhieuBanListResponse> | null;
};

export type KhachHangResponse = {
    maKH?: string;
    maKHCode?: string | null;
    tenKH?: string | null;
    soDienThoai?: string | null;
    diaChi?: string | null;
    loaiKhachHang?: string | null;
    hanMucCongNo?: number | null;
    tongMua?: number;
    congNoHienTai?: number;
    trangThai?: string | null;
    ghiChu?: string | null;
    ngayTao?: string;
};

export type KhachHangResponsePagedResult = {
    items?: Array<KhachHangResponse> | null;
    total?: number;
    page?: number | null;
    pageSize?: number | null;
};

export type KhachHangUpdateRequest = {
    tenKH: string;
    soDienThoai?: string | null;
    diaChi?: string | null;
    loaiKhachHang: LoaiKhachHangEnum;
    hanMucCongNo?: number | null;
    trangThai: TrangThaiKhachHangEnum;
    ghiChu?: string | null;
};

export type KhoHangResponse = {
    maKho?: string;
    maKhoCode?: string | null;
    tenKho?: string | null;
    diaChi?: string | null;
    trangThai?: string | null;
    ghiChu?: string | null;
};

export type LoHangRequest = {
    maSP?: string;
    ngaySanXuat?: string | null;
    hanSuDung?: string;
};

export type LoHangResponse = {
    maLo?: string;
    maLoCode?: string | null;
    maSP?: string;
    tenSP?: string | null;
    ngaySanXuat?: string | null;
    hanSuDung?: string;
};

export type LoaiKhachHangEnum = 0 | 1 | 2;

export type LoginRequest = {
    email: string;
    password: string;
};

export type NhaCungCapCreateRequest = {
    tenNCC?: string | null;
    soDienThoai?: string | null;
    diaChi?: string | null;
    trangThai?: string | null;
    ghiChu?: string | null;
    sanPhams?: Array<NhaCungCapSanPhamItemDto> | null;
};

export type NhaCungCapDetailedResponse = {
    maNCC?: string;
    maNCCCode?: string | null;
    tenNCC?: string | null;
    soDienThoai?: string | null;
    diaChi?: string | null;
    trangThai?: string | null;
    ghiChu?: string | null;
    ngayTao?: string;
    sanPhams?: Array<NhaCungCapSanPhamResponse> | null;
};

export type NhaCungCapResponse = {
    maNCC?: string;
    maNCCCode?: string | null;
    tenNCC?: string | null;
    soDienThoai?: string | null;
    diaChi?: string | null;
    trangThai?: string | null;
    ghiChu?: string | null;
    ngayTao?: string;
    sanPhamCount?: number;
};

export type NhaCungCapSanPhamItemDto = {
    maSP?: string;
    giaNhapMacDinh?: number | null;
    trangThai?: string | null;
    ghiChu?: string | null;
};

export type NhaCungCapSanPhamResponse = {
    maNCSP?: string;
    maSP?: string;
    tenSanPham?: string | null;
    maSanPhamCode?: string | null;
    donViCoSo?: string | null;
    giaNhapMacDinh?: number;
    ghiChu?: string | null;
    trangThai?: string | null;
};

export type NhaCungCapUpdateRequest = {
    tenNCC?: string | null;
    soDienThoai?: string | null;
    diaChi?: string | null;
    trangThai?: string | null;
    ghiChu?: string | null;
    sanPhams?: Array<NhaCungCapSanPhamItemDto> | null;
};

export type PhieuBanDetailResponse = {
    maPB?: string;
    maPBCode?: string | null;
    maKH?: string;
    tenKhachHang?: string | null;
    ngayBan?: string;
    tongTienHang?: number;
    chietKhauPhanTram?: number;
    tienChietKhau?: number;
    thanhTien?: number;
    hinhThucThanhToan?: string | null;
    trangThaiThanhToan?: string | null;
    tienCoc?: number;
    tienNo?: number;
    hanTra?: string | null;
    ghiChu?: string | null;
    danhSachChiTiet?: Array<ChiTietPhieuBanResponse> | null;
};

export type PhieuBanListResponse = {
    maPB?: string;
    maPBCode?: string | null;
    ngayBan?: string;
    tongTienHang?: number;
    tienChietKhau?: number;
    thanhTien?: number;
    hinhThucThanhToan?: string | null;
    trangThaiThanhToan?: string | null;
    tienNo?: number;
    ghiChu?: string | null;
};

export type PhieuBanResponse = {
    maPB?: string;
    maPBCode?: string | null;
    maKH?: string;
    tenKhachHang?: string | null;
    ngayBan?: string;
    tongTienHang?: number;
    chietKhauPhanTram?: number;
    tienChietKhau?: number;
    thanhTien?: number;
    hinhThucThanhToan?: string | null;
    trangThaiThanhToan?: string | null;
    tienCoc?: number;
    tienNo?: number;
    hanTra?: string | null;
    ghiChu?: string | null;
};

export type PhieuChuyenKhoRequest = {
    ngayLap?: string;
    maKhoXuat: string;
    maKhoNhan: string;
    ghiChu?: string | null;
    danhSachSanPham: Array<CtChuyenKhoRequest>;
};

export type PhieuChuyenKhoResponse = {
    maCK?: string;
    maCKCode?: string | null;
    ngayLap?: string;
    tenKhoXuat?: string | null;
    tenKhoNhan?: string | null;
    ghiChu?: string | null;
};

export type PhieuNhapCreateRequest = {
    maNCC?: string;
    maKho?: string;
    ghiChu?: string | null;
    danhSachChiTiet?: Array<CtPhieuNhapRequest> | null;
};

export type PhieuNhapDetailedResponse = {
    maPN?: string;
    maPNCode?: string | null;
    maNCC?: string;
    tenNCC?: string | null;
    maKho?: string;
    tenKho?: string | null;
    thanhTien?: number;
    trangThai?: string | null;
    ghiChu?: string | null;
    ngayCapNhat?: string;
    danhSachChiTiet?: Array<CtPhieuNhapResponse> | null;
};

export type PhieuNhapResponse = {
    maPN?: string;
    maPNCode?: string | null;
    maNCC?: string;
    tenNCC?: string | null;
    maKho?: string;
    tenKho?: string | null;
    thanhTien?: number;
    trangThai?: string | null;
    ghiChu?: string | null;
    ngayCapNhat?: string;
};

export type PhieuNhapUpdateRequest = {
    maNCC?: string;
    maKho?: string;
    trangThai?: string | null;
    ghiChu?: string | null;
    thanhTien?: number;
    danhSachChiTiet?: Array<CtPhieuNhapUpdateRequest> | null;
};

export type PhieuTraDetailResponse = {
    maPT?: string;
    maPTCode?: string | null;
    maPB?: string;
    maPBCode?: string | null;
    maKH?: string;
    tenKhachHang?: string | null;
    ngayTra?: string;
    thanhTien?: number;
    lyDoTra?: string | null;
    hinhThucHoanTien?: string | null;
    danhSachChiTiet?: Array<ChiTietPhieuTraDetailResponse> | null;
};

export type PhieuTraListResponse = {
    maPT?: string;
    maPTCode?: string | null;
    ngayTra?: string;
    maPB?: string;
    maPBCode?: string | null;
    maKH?: string;
    tenKhachHang?: string | null;
    thanhTien?: number;
    hinhThucHoanTien?: string | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type SanPhamCreateRequest = {
    tenSP: string;
    loaiSanPham: string;
    donViTinh?: string | null;
    ghiChu?: string | null;
    giaBanDau?: number | null;
    donViQuyDoi?: Array<DonViQuyDoiItem> | null;
};

export type SanPhamResponse = {
    maSP?: string;
    maSPCode?: string | null;
    tenSP?: string | null;
    loaiSanPham?: string | null;
    donViCoSo?: string | null;
    ghiChu?: string | null;
    ngayTao?: string;
    donGia?: number | null;
    donViQuyDoi?: Array<DonViQuyDoiItem> | null;
};

export type SanPhamResponsePagedResult = {
    items?: Array<SanPhamResponse> | null;
    total?: number;
    page?: number | null;
    pageSize?: number | null;
};

export type SanPhamUpdateRequest = {
    tenSP: string;
    loaiSanPham: string;
    donViTinh?: string | null;
    ghiChu?: string | null;
    giaMoi?: number | null;
    donViQuyDoi?: Array<DonViQuyDoiItem> | null;
};

export type SearchKhoHangRequest = {
    thuocTinh?: string | null;
    keyWord?: string | null;
};

export type TrangThaiKhachHangEnum = 0 | 1;

export type TrangThaiKhoEnum = 0 | 1;

export type TrangThaiPhieuChuyenKhoChiTietEnum = 0 | 1 | 2;

export type UpdateKhoHangRequest = {
    tenKho: string;
    diaChi: string;
    trangThai: TrangThaiKhoEnum;
    ghiChu?: string | null;
};

export type UpdatePasswordRequest = {
    email: string;
    password: string;
};

export type UpdatePhieuChuyenKhoRequest = {
    maCK: string;
    ngayLap?: string;
    maKhoNhan: string;
    ghiChu?: string | null;
    danhSachChiTiet?: Array<ChiTietChuyenKhoUpdateItem> | null;
};

export type UpdateTaiKhoanRequest = {
    email?: string | null;
    hoTen?: string | null;
    soDienThoai?: string | null;
    anhDaiDien?: string | null;
};

export type UpdateTonKhoRequest = {
    soLuong?: number;
};

export type UpdateTrangThaiCtChuyenKho = {
    trangThai: TrangThaiPhieuChuyenKhoChiTietEnum;
};

export type CtPhieuNhapResponseWritable = {
    maCTPN?: string;
    maPN?: string;
    maLo?: string;
    maLoCode?: string | null;
    tenSP?: string | null;
    ngaySanXuat?: string | null;
    hanSuDung?: string | null;
    soLuong?: number;
    donGia?: number | null;
    donViNhap?: string | null;
    soLuongQuyDoi?: number;
    donGiaCoSo?: number;
};

export type PhieuNhapDetailedResponseWritable = {
    maPN?: string;
    maPNCode?: string | null;
    maNCC?: string;
    tenNCC?: string | null;
    maKho?: string;
    tenKho?: string | null;
    thanhTien?: number;
    trangThai?: string | null;
    ghiChu?: string | null;
    ngayCapNhat?: string;
    danhSachChiTiet?: Array<CtPhieuNhapResponseWritable> | null;
};

export type GetApiCongNosSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/CongNos/summary';
};

export type GetApiCongNosSummaryResponses = {
    /**
     * OK
     */
    200: Array<CongNoTongHopResponse>;
};

export type GetApiCongNosSummaryResponse = GetApiCongNosSummaryResponses[keyof GetApiCongNosSummaryResponses];

export type GetApiCongNosByMaDoiTuongDetailData = {
    body?: never;
    path: {
        maDoiTuong: string;
    };
    query?: never;
    url: '/api/CongNos/{maDoiTuong}/detail';
};

export type GetApiCongNosByMaDoiTuongDetailResponses = {
    /**
     * OK
     */
    200: Array<CongNoHistoryResponse>;
};

export type GetApiCongNosByMaDoiTuongDetailResponse = GetApiCongNosByMaDoiTuongDetailResponses[keyof GetApiCongNosByMaDoiTuongDetailResponses];

export type PostApiCongNosData = {
    body?: CreateCongNoRequest;
    path?: never;
    query?: never;
    url: '/api/CongNos';
};

export type PostApiCongNosErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiCongNosError = PostApiCongNosErrors[keyof PostApiCongNosErrors];

export type PostApiCongNosResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiGiaBansData = {
    body?: never;
    path?: never;
    query?: {
        MaSP?: string;
        From?: string;
        To?: string;
        Page?: number;
        PageSize?: number;
    };
    url: '/api/GiaBans';
};

export type GetApiGiaBansResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiGiaBansData = {
    body?: GiaBanCreateRequest;
    path?: never;
    query?: never;
    url: '/api/GiaBans';
};

export type PostApiGiaBansResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiGiaBansByMaGiaData = {
    body?: never;
    path: {
        maGia: string;
    };
    query?: never;
    url: '/api/GiaBans/{maGia}';
};

export type DeleteApiGiaBansByMaGiaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGiaBansByMaGiaData = {
    body?: never;
    path: {
        maGia: string;
    };
    query?: never;
    url: '/api/GiaBans/{maGia}';
};

export type GetApiGiaBansByMaGiaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiGiaBansByMaGiaData = {
    body?: GiaBanUpdateRequest;
    path: {
        maGia: string;
    };
    query?: never;
    url: '/api/GiaBans/{maGia}';
};

export type PutApiGiaBansByMaGiaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGiaBansCurrentData = {
    body?: never;
    path?: never;
    query?: {
        maSP?: string;
        date?: string;
    };
    url: '/api/GiaBans/current';
};

export type GetApiGiaBansCurrentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiKhachHangsData = {
    body?: never;
    path?: never;
    query?: {
        Keyword?: string;
        LoaiKhachHang?: string;
        TrangThai?: string;
        Page?: number;
        PageSize?: number;
    };
    url: '/api/KhachHangs';
};

export type GetApiKhachHangsResponses = {
    /**
     * OK
     */
    200: KhachHangResponsePagedResult;
};

export type GetApiKhachHangsResponse = GetApiKhachHangsResponses[keyof GetApiKhachHangsResponses];

export type PostApiKhachHangsData = {
    body?: KhachHangCreateRequest;
    path?: never;
    query?: never;
    url: '/api/KhachHangs';
};

export type PostApiKhachHangsResponses = {
    /**
     * OK
     */
    200: KhachHangResponse;
};

export type PostApiKhachHangsResponse = PostApiKhachHangsResponses[keyof PostApiKhachHangsResponses];

export type GetApiKhachHangsByCodeByMaKhCodeData = {
    body?: never;
    path: {
        maKHCode: string;
    };
    query?: never;
    url: '/api/KhachHangs/by-code/{maKHCode}';
};

export type GetApiKhachHangsByCodeByMaKhCodeResponses = {
    /**
     * OK
     */
    200: KhachHangResponse;
};

export type GetApiKhachHangsByCodeByMaKhCodeResponse = GetApiKhachHangsByCodeByMaKhCodeResponses[keyof GetApiKhachHangsByCodeByMaKhCodeResponses];

export type GetApiKhachHangsByPhoneData = {
    body?: never;
    path?: never;
    query?: {
        phone?: string;
    };
    url: '/api/KhachHangs/by-phone';
};

export type GetApiKhachHangsByPhoneResponses = {
    /**
     * OK
     */
    200: KhachHangResponse;
};

export type GetApiKhachHangsByPhoneResponse = GetApiKhachHangsByPhoneResponses[keyof GetApiKhachHangsByPhoneResponses];

export type DeleteApiKhachHangsByMaKhData = {
    body?: never;
    path: {
        maKH: string;
    };
    query?: never;
    url: '/api/KhachHangs/{maKH}';
};

export type DeleteApiKhachHangsByMaKhResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiKhachHangsByMaKhData = {
    body?: never;
    path: {
        maKH: string;
    };
    query?: never;
    url: '/api/KhachHangs/{maKH}';
};

export type GetApiKhachHangsByMaKhResponses = {
    /**
     * OK
     */
    200: KhachHangResponse;
};

export type GetApiKhachHangsByMaKhResponse = GetApiKhachHangsByMaKhResponses[keyof GetApiKhachHangsByMaKhResponses];

export type PutApiKhachHangsByMaKhData = {
    body?: KhachHangUpdateRequest;
    path: {
        maKH: string;
    };
    query?: never;
    url: '/api/KhachHangs/{maKH}';
};

export type PutApiKhachHangsByMaKhResponses = {
    /**
     * OK
     */
    200: KhachHangResponse;
};

export type PutApiKhachHangsByMaKhResponse = PutApiKhachHangsByMaKhResponses[keyof PutApiKhachHangsByMaKhResponses];

export type GetApiKhoHangsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/KhoHangs';
};

export type GetApiKhoHangsResponses = {
    /**
     * OK
     */
    200: Array<KhoHangResponse>;
};

export type GetApiKhoHangsResponse = GetApiKhoHangsResponses[keyof GetApiKhoHangsResponses];

export type PostApiKhoHangsData = {
    body?: CreateKhoHangRequest;
    path?: never;
    query?: never;
    url: '/api/KhoHangs';
};

export type PostApiKhoHangsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiKhoHangsError = PostApiKhoHangsErrors[keyof PostApiKhoHangsErrors];

export type PostApiKhoHangsResponses = {
    /**
     * Created
     */
    201: KhoHangResponse;
};

export type PostApiKhoHangsResponse = PostApiKhoHangsResponses[keyof PostApiKhoHangsResponses];

export type DeleteApiKhoHangsByMaKhoData = {
    body?: never;
    path: {
        maKho: string;
    };
    query?: never;
    url: '/api/KhoHangs/{maKho}';
};

export type DeleteApiKhoHangsByMaKhoErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiKhoHangsByMaKhoError = DeleteApiKhoHangsByMaKhoErrors[keyof DeleteApiKhoHangsByMaKhoErrors];

export type DeleteApiKhoHangsByMaKhoResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiKhoHangsByMaKhoResponse = DeleteApiKhoHangsByMaKhoResponses[keyof DeleteApiKhoHangsByMaKhoResponses];

export type GetKhoHangByIdData = {
    body?: never;
    path: {
        maKho: string;
    };
    query?: never;
    url: '/api/KhoHangs/{maKho}';
};

export type GetKhoHangByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetKhoHangByIdError = GetKhoHangByIdErrors[keyof GetKhoHangByIdErrors];

export type GetKhoHangByIdResponses = {
    /**
     * OK
     */
    200: KhoHangResponse;
};

export type GetKhoHangByIdResponse = GetKhoHangByIdResponses[keyof GetKhoHangByIdResponses];

export type PutApiKhoHangsByMaKhoData = {
    body?: UpdateKhoHangRequest;
    path: {
        maKho: string;
    };
    query?: never;
    url: '/api/KhoHangs/{maKho}';
};

export type PutApiKhoHangsByMaKhoErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PutApiKhoHangsByMaKhoError = PutApiKhoHangsByMaKhoErrors[keyof PutApiKhoHangsByMaKhoErrors];

export type PutApiKhoHangsByMaKhoResponses = {
    /**
     * OK
     */
    200: KhoHangResponse;
};

export type PutApiKhoHangsByMaKhoResponse = PutApiKhoHangsByMaKhoResponses[keyof PutApiKhoHangsByMaKhoResponses];

export type PostApiKhoHangsSearchData = {
    body?: SearchKhoHangRequest;
    path?: never;
    query?: never;
    url: '/api/KhoHangs/search';
};

export type PostApiKhoHangsSearchResponses = {
    /**
     * OK
     */
    200: Array<KhoHangResponse>;
};

export type PostApiKhoHangsSearchResponse = PostApiKhoHangsSearchResponses[keyof PostApiKhoHangsSearchResponses];

export type GetApiLoHangsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/LoHangs';
};

export type GetApiLoHangsResponses = {
    /**
     * OK
     */
    200: Array<LoHangResponse>;
};

export type GetApiLoHangsResponse = GetApiLoHangsResponses[keyof GetApiLoHangsResponses];

export type PostApiLoHangsData = {
    body?: LoHangRequest;
    path?: never;
    query?: never;
    url: '/api/LoHangs';
};

export type PostApiLoHangsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiLoHangsError = PostApiLoHangsErrors[keyof PostApiLoHangsErrors];

export type PostApiLoHangsResponses = {
    /**
     * Created
     */
    201: LoHangResponse;
};

export type PostApiLoHangsResponse = PostApiLoHangsResponses[keyof PostApiLoHangsResponses];

export type DeleteApiLoHangsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/LoHangs/{id}';
};

export type DeleteApiLoHangsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiLoHangsByIdError = DeleteApiLoHangsByIdErrors[keyof DeleteApiLoHangsByIdErrors];

export type DeleteApiLoHangsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiLoHangsByIdResponse = DeleteApiLoHangsByIdResponses[keyof DeleteApiLoHangsByIdResponses];

export type GetApiLoHangsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/LoHangs/{id}';
};

export type GetApiLoHangsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiLoHangsByIdError = GetApiLoHangsByIdErrors[keyof GetApiLoHangsByIdErrors];

export type GetApiLoHangsByIdResponses = {
    /**
     * OK
     */
    200: LoHangResponse;
};

export type GetApiLoHangsByIdResponse = GetApiLoHangsByIdResponses[keyof GetApiLoHangsByIdResponses];

export type PutApiLoHangsByIdData = {
    body?: LoHangRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/LoHangs/{id}';
};

export type PutApiLoHangsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiLoHangsByIdError = PutApiLoHangsByIdErrors[keyof PutApiLoHangsByIdErrors];

export type PutApiLoHangsByIdResponses = {
    /**
     * OK
     */
    200: LoHangResponse;
};

export type PutApiLoHangsByIdResponse = PutApiLoHangsByIdResponses[keyof PutApiLoHangsByIdResponses];

export type GetApiLoHangsBysanphamByMaSpData = {
    body?: never;
    path: {
        maSP: string;
    };
    query?: never;
    url: '/api/LoHangs/bysanpham/{maSP}';
};

export type GetApiLoHangsBysanphamByMaSpResponses = {
    /**
     * OK
     */
    200: Array<LoHangResponse>;
};

export type GetApiLoHangsBysanphamByMaSpResponse = GetApiLoHangsBysanphamByMaSpResponses[keyof GetApiLoHangsBysanphamByMaSpResponses];

export type GetApiLoHangsOutdatedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/LoHangs/outdated';
};

export type GetApiLoHangsOutdatedResponses = {
    /**
     * OK
     */
    200: LoHangResponse;
};

export type GetApiLoHangsOutdatedResponse = GetApiLoHangsOutdatedResponses[keyof GetApiLoHangsOutdatedResponses];

export type GetApiNhaCungCapsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/NhaCungCaps';
};

export type GetApiNhaCungCapsResponses = {
    /**
     * OK
     */
    200: Array<NhaCungCapResponse>;
};

export type GetApiNhaCungCapsResponse = GetApiNhaCungCapsResponses[keyof GetApiNhaCungCapsResponses];

export type PostApiNhaCungCapsData = {
    body?: NhaCungCapCreateRequest;
    path?: never;
    query?: never;
    url: '/api/NhaCungCaps';
};

export type PostApiNhaCungCapsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiNhaCungCapsError = PostApiNhaCungCapsErrors[keyof PostApiNhaCungCapsErrors];

export type PostApiNhaCungCapsResponses = {
    /**
     * Created
     */
    201: NhaCungCapDetailedResponse;
};

export type PostApiNhaCungCapsResponse = PostApiNhaCungCapsResponses[keyof PostApiNhaCungCapsResponses];

export type DeleteApiNhaCungCapsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/NhaCungCaps/{id}';
};

export type DeleteApiNhaCungCapsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiNhaCungCapsByIdError = DeleteApiNhaCungCapsByIdErrors[keyof DeleteApiNhaCungCapsByIdErrors];

export type DeleteApiNhaCungCapsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiNhaCungCapsByIdResponse = DeleteApiNhaCungCapsByIdResponses[keyof DeleteApiNhaCungCapsByIdResponses];

export type GetApiNhaCungCapsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/NhaCungCaps/{id}';
};

export type GetApiNhaCungCapsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiNhaCungCapsByIdError = GetApiNhaCungCapsByIdErrors[keyof GetApiNhaCungCapsByIdErrors];

export type GetApiNhaCungCapsByIdResponses = {
    /**
     * OK
     */
    200: NhaCungCapDetailedResponse;
};

export type GetApiNhaCungCapsByIdResponse = GetApiNhaCungCapsByIdResponses[keyof GetApiNhaCungCapsByIdResponses];

export type PutApiNhaCungCapsByIdData = {
    body?: NhaCungCapUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/NhaCungCaps/{id}';
};

export type PutApiNhaCungCapsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiNhaCungCapsByIdError = PutApiNhaCungCapsByIdErrors[keyof PutApiNhaCungCapsByIdErrors];

export type PutApiNhaCungCapsByIdResponses = {
    /**
     * OK
     */
    200: NhaCungCapDetailedResponse;
};

export type PutApiNhaCungCapsByIdResponse = PutApiNhaCungCapsByIdResponses[keyof PutApiNhaCungCapsByIdResponses];

export type GetApiPhieuBansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PhieuBans';
};

export type GetApiPhieuBansErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetApiPhieuBansResponses = {
    /**
     * OK
     */
    200: Array<PhieuBanResponse>;
};

export type GetApiPhieuBansResponse = GetApiPhieuBansResponses[keyof GetApiPhieuBansResponses];

export type PostApiPhieuBansData = {
    body?: CreatePhieuBanRequest;
    path?: never;
    query?: never;
    url: '/api/PhieuBans';
};

export type PostApiPhieuBansErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiPhieuBansError = PostApiPhieuBansErrors[keyof PostApiPhieuBansErrors];

export type PostApiPhieuBansResponses = {
    /**
     * Created
     */
    201: PhieuBanResponse;
};

export type PostApiPhieuBansResponse = PostApiPhieuBansResponses[keyof PostApiPhieuBansResponses];

export type DeleteApiPhieuBansByMaPbData = {
    body?: never;
    path: {
        maPB: string;
    };
    query?: never;
    url: '/api/PhieuBans/{maPB}';
};

export type DeleteApiPhieuBansByMaPbErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiPhieuBansByMaPbError = DeleteApiPhieuBansByMaPbErrors[keyof DeleteApiPhieuBansByMaPbErrors];

export type DeleteApiPhieuBansByMaPbResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPhieuBansByMaPbData = {
    body?: never;
    path: {
        maPB: string;
    };
    query?: never;
    url: '/api/PhieuBans/{maPB}';
};

export type GetApiPhieuBansByMaPbErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiPhieuBansByMaPbError = GetApiPhieuBansByMaPbErrors[keyof GetApiPhieuBansByMaPbErrors];

export type GetApiPhieuBansByMaPbResponses = {
    /**
     * OK
     */
    200: PhieuBanDetailResponse;
};

export type GetApiPhieuBansByMaPbResponse = GetApiPhieuBansByMaPbResponses[keyof GetApiPhieuBansByMaPbResponses];

export type GetApiPhieuBansKhachhangByMaKhData = {
    body?: never;
    path: {
        maKH: string;
    };
    query?: never;
    url: '/api/PhieuBans/khachhang/{maKH}';
};

export type GetApiPhieuBansKhachhangByMaKhErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiPhieuBansKhachhangByMaKhError = GetApiPhieuBansKhachhangByMaKhErrors[keyof GetApiPhieuBansKhachhangByMaKhErrors];

export type GetApiPhieuBansKhachhangByMaKhResponses = {
    /**
     * OK
     */
    200: KhachHangPhieuBanResponse;
};

export type GetApiPhieuBansKhachhangByMaKhResponse = GetApiPhieuBansKhachhangByMaKhResponses[keyof GetApiPhieuBansKhachhangByMaKhResponses];

export type GetApiPhieuChuyenKhosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PhieuChuyenKhos';
};

export type GetApiPhieuChuyenKhosResponses = {
    /**
     * OK
     */
    200: Array<PhieuChuyenKhoResponse>;
};

export type GetApiPhieuChuyenKhosResponse = GetApiPhieuChuyenKhosResponses[keyof GetApiPhieuChuyenKhosResponses];

export type PostApiPhieuChuyenKhosData = {
    body?: PhieuChuyenKhoRequest;
    path?: never;
    query?: never;
    url: '/api/PhieuChuyenKhos';
};

export type PostApiPhieuChuyenKhosErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiPhieuChuyenKhosError = PostApiPhieuChuyenKhosErrors[keyof PostApiPhieuChuyenKhosErrors];

export type PostApiPhieuChuyenKhosResponses = {
    /**
     * OK
     */
    200: PhieuChuyenKhoResponse;
};

export type PostApiPhieuChuyenKhosResponse = PostApiPhieuChuyenKhosResponses[keyof PostApiPhieuChuyenKhosResponses];

export type DeleteApiPhieuChuyenKhosByMaCkData = {
    body?: never;
    path: {
        maCK: string;
    };
    query?: never;
    url: '/api/PhieuChuyenKhos/{maCK}';
};

export type DeleteApiPhieuChuyenKhosByMaCkErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiPhieuChuyenKhosByMaCkError = DeleteApiPhieuChuyenKhosByMaCkErrors[keyof DeleteApiPhieuChuyenKhosByMaCkErrors];

export type DeleteApiPhieuChuyenKhosByMaCkResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPhieuChuyenKhosByMaCkData = {
    body?: never;
    path: {
        maCK: string;
    };
    query?: never;
    url: '/api/PhieuChuyenKhos/{maCK}';
};

export type GetApiPhieuChuyenKhosByMaCkErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiPhieuChuyenKhosByMaCkError = GetApiPhieuChuyenKhosByMaCkErrors[keyof GetApiPhieuChuyenKhosByMaCkErrors];

export type GetApiPhieuChuyenKhosByMaCkResponses = {
    /**
     * OK
     */
    200: ChiTietPhieuChuyenKhoResponse;
};

export type GetApiPhieuChuyenKhosByMaCkResponse = GetApiPhieuChuyenKhosByMaCkResponses[keyof GetApiPhieuChuyenKhosByMaCkResponses];

export type PutApiPhieuChuyenKhosByMaCkData = {
    body?: UpdatePhieuChuyenKhoRequest;
    path: {
        maCK: string;
    };
    query?: never;
    url: '/api/PhieuChuyenKhos/{maCK}';
};

export type PutApiPhieuChuyenKhosByMaCkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiPhieuChuyenKhosByMaCkError = PutApiPhieuChuyenKhosByMaCkErrors[keyof PutApiPhieuChuyenKhosByMaCkErrors];

export type PutApiPhieuChuyenKhosByMaCkResponses = {
    /**
     * OK
     */
    200: PhieuChuyenKhoResponse;
};

export type PutApiPhieuChuyenKhosByMaCkResponse = PutApiPhieuChuyenKhosByMaCkResponses[keyof PutApiPhieuChuyenKhosByMaCkResponses];

export type PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiData = {
    body?: UpdateTrangThaiCtChuyenKho;
    path: {
        maCTCK: string;
    };
    query?: never;
    url: '/api/PhieuChuyenKhos/chitiet/{maCTCK}/trangthai';
};

export type PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiError = PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiErrors[keyof PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiErrors];

export type PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiResponses = {
    /**
     * OK
     */
    200: ChiTietPhieuChuyenKhoResponse;
};

export type PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiResponse = PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiResponses[keyof PutApiPhieuChuyenKhosChitietByMaCtckTrangthaiResponses];

export type GetApiPhieuNhapsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PhieuNhaps';
};

export type GetApiPhieuNhapsResponses = {
    /**
     * OK
     */
    200: Array<PhieuNhapResponse>;
};

export type GetApiPhieuNhapsResponse = GetApiPhieuNhapsResponses[keyof GetApiPhieuNhapsResponses];

export type PostApiPhieuNhapsData = {
    body?: PhieuNhapCreateRequest;
    path?: never;
    query?: never;
    url: '/api/PhieuNhaps';
};

export type PostApiPhieuNhapsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiPhieuNhapsError = PostApiPhieuNhapsErrors[keyof PostApiPhieuNhapsErrors];

export type PostApiPhieuNhapsResponses = {
    /**
     * Created
     */
    201: PhieuNhapDetailedResponse;
};

export type PostApiPhieuNhapsResponse = PostApiPhieuNhapsResponses[keyof PostApiPhieuNhapsResponses];

export type DeleteApiPhieuNhapsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PhieuNhaps/{id}';
};

export type DeleteApiPhieuNhapsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiPhieuNhapsByIdError = DeleteApiPhieuNhapsByIdErrors[keyof DeleteApiPhieuNhapsByIdErrors];

export type DeleteApiPhieuNhapsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPhieuNhapsByIdResponse = DeleteApiPhieuNhapsByIdResponses[keyof DeleteApiPhieuNhapsByIdResponses];

export type GetApiPhieuNhapsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PhieuNhaps/{id}';
};

export type GetApiPhieuNhapsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiPhieuNhapsByIdError = GetApiPhieuNhapsByIdErrors[keyof GetApiPhieuNhapsByIdErrors];

export type GetApiPhieuNhapsByIdResponses = {
    /**
     * OK
     */
    200: PhieuNhapDetailedResponse;
};

export type GetApiPhieuNhapsByIdResponse = GetApiPhieuNhapsByIdResponses[keyof GetApiPhieuNhapsByIdResponses];

export type PutApiPhieuNhapsByIdData = {
    body?: PhieuNhapUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PhieuNhaps/{id}';
};

export type PutApiPhieuNhapsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiPhieuNhapsByIdError = PutApiPhieuNhapsByIdErrors[keyof PutApiPhieuNhapsByIdErrors];

export type PutApiPhieuNhapsByIdResponses = {
    /**
     * OK
     */
    200: PhieuNhapDetailedResponse;
};

export type PutApiPhieuNhapsByIdResponse = PutApiPhieuNhapsByIdResponses[keyof PutApiPhieuNhapsByIdResponses];

export type GetApiPhieuTrasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PhieuTras';
};

export type GetApiPhieuTrasErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetApiPhieuTrasResponses = {
    /**
     * OK
     */
    200: Array<PhieuTraListResponse>;
};

export type GetApiPhieuTrasResponse = GetApiPhieuTrasResponses[keyof GetApiPhieuTrasResponses];

export type PostApiPhieuTrasData = {
    body?: CreatePhieuTraRequest;
    path?: never;
    query?: never;
    url: '/api/PhieuTras';
};

export type PostApiPhieuTrasErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiPhieuTrasError = PostApiPhieuTrasErrors[keyof PostApiPhieuTrasErrors];

export type PostApiPhieuTrasResponses = {
    /**
     * Created
     */
    201: PhieuTraDetailResponse;
};

export type PostApiPhieuTrasResponse = PostApiPhieuTrasResponses[keyof PostApiPhieuTrasResponses];

export type DeleteApiPhieuTrasByMaPtData = {
    body?: never;
    path: {
        maPT: string;
    };
    query?: never;
    url: '/api/PhieuTras/{maPT}';
};

export type DeleteApiPhieuTrasByMaPtErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteApiPhieuTrasByMaPtError = DeleteApiPhieuTrasByMaPtErrors[keyof DeleteApiPhieuTrasByMaPtErrors];

export type DeleteApiPhieuTrasByMaPtResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPhieuTrasByMaPtData = {
    body?: never;
    path: {
        maPT: string;
    };
    query?: never;
    url: '/api/PhieuTras/{maPT}';
};

export type GetApiPhieuTrasByMaPtErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetApiPhieuTrasByMaPtError = GetApiPhieuTrasByMaPtErrors[keyof GetApiPhieuTrasByMaPtErrors];

export type GetApiPhieuTrasByMaPtResponses = {
    /**
     * OK
     */
    200: PhieuTraDetailResponse;
};

export type GetApiPhieuTrasByMaPtResponse = GetApiPhieuTrasByMaPtResponses[keyof GetApiPhieuTrasByMaPtResponses];

export type PostApiPhieuTrasCheckReturnableData = {
    body?: CheckReturnableRequest;
    path?: never;
    query?: never;
    url: '/api/PhieuTras/check-returnable';
};

export type PostApiPhieuTrasCheckReturnableErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiPhieuTrasCheckReturnableError = PostApiPhieuTrasCheckReturnableErrors[keyof PostApiPhieuTrasCheckReturnableErrors];

export type PostApiPhieuTrasCheckReturnableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PostApiPhieuTrasCheckReturnableResponse = PostApiPhieuTrasCheckReturnableResponses[keyof PostApiPhieuTrasCheckReturnableResponses];

export type GetApiSanPhamsData = {
    body?: never;
    path?: never;
    query?: {
        Keyword?: string;
        LoaiSanPham?: string;
        Page?: number;
        PageSize?: number;
    };
    url: '/api/SanPhams';
};

export type GetApiSanPhamsResponses = {
    /**
     * OK
     */
    200: SanPhamResponsePagedResult;
};

export type GetApiSanPhamsResponse = GetApiSanPhamsResponses[keyof GetApiSanPhamsResponses];

export type PostApiSanPhamsData = {
    body?: SanPhamCreateRequest;
    path?: never;
    query?: never;
    url: '/api/SanPhams';
};

export type PostApiSanPhamsResponses = {
    /**
     * OK
     */
    200: SanPhamResponse;
};

export type PostApiSanPhamsResponse = PostApiSanPhamsResponses[keyof PostApiSanPhamsResponses];

export type GetApiSanPhamsByCodeByMaSpCodeData = {
    body?: never;
    path: {
        maSPCode: string;
    };
    query?: never;
    url: '/api/SanPhams/by-code/{maSPCode}';
};

export type GetApiSanPhamsByCodeByMaSpCodeResponses = {
    /**
     * OK
     */
    200: SanPhamResponse;
};

export type GetApiSanPhamsByCodeByMaSpCodeResponse = GetApiSanPhamsByCodeByMaSpCodeResponses[keyof GetApiSanPhamsByCodeByMaSpCodeResponses];

export type DeleteApiSanPhamsByMaSpData = {
    body?: never;
    path: {
        maSP: string;
    };
    query?: never;
    url: '/api/SanPhams/{maSP}';
};

export type DeleteApiSanPhamsByMaSpResponses = {
    /**
     * OK
     */
    200: string;
};

export type DeleteApiSanPhamsByMaSpResponse = DeleteApiSanPhamsByMaSpResponses[keyof DeleteApiSanPhamsByMaSpResponses];

export type GetApiSanPhamsByMaSpData = {
    body?: never;
    path: {
        maSP: string;
    };
    query?: never;
    url: '/api/SanPhams/{maSP}';
};

export type GetApiSanPhamsByMaSpResponses = {
    /**
     * OK
     */
    200: SanPhamResponse;
};

export type GetApiSanPhamsByMaSpResponse = GetApiSanPhamsByMaSpResponses[keyof GetApiSanPhamsByMaSpResponses];

export type PutApiSanPhamsByMaSpData = {
    body?: SanPhamUpdateRequest;
    path: {
        maSP: string;
    };
    query?: never;
    url: '/api/SanPhams/{maSP}';
};

export type PutApiSanPhamsByMaSpResponses = {
    /**
     * OK
     */
    200: SanPhamResponse;
};

export type PutApiSanPhamsByMaSpResponse = PutApiSanPhamsByMaSpResponses[keyof PutApiSanPhamsByMaSpResponses];

export type GetTaiKhoanByIdData = {
    body?: never;
    path: {
        maTK: string;
    };
    query?: never;
    url: '/api/TaiKhoans/{maTK}';
};

export type GetTaiKhoanByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiTaiKhoansByMaTkData = {
    body?: UpdateTaiKhoanRequest;
    path: {
        maTK: string;
    };
    query?: never;
    url: '/api/TaiKhoans/{maTK}';
};

export type PutApiTaiKhoansByMaTkResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTaiKhoansSignupData = {
    body?: CreateTaiKhoanRequest;
    path?: never;
    query?: never;
    url: '/api/TaiKhoans/signup';
};

export type PostApiTaiKhoansSignupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTaiKhoansLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/TaiKhoans/login';
};

export type PostApiTaiKhoansLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTaiKhoansLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/TaiKhoans/logout';
};

export type PostApiTaiKhoansLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTaiKhoansResetPasswordData = {
    body?: UpdatePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/TaiKhoans/reset-password';
};

export type PostApiTaiKhoansResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTaiKhoansForgotPasswordData = {
    body?: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/TaiKhoans/forgot-password';
};

export type PostApiTaiKhoansForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTonKhosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/TonKhos';
};

export type GetApiTonKhosResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiTonKhosByMaKhoByMaLoData = {
    body?: UpdateTonKhoRequest;
    path: {
        maKho: string;
        maLo: string;
    };
    query?: never;
    url: '/api/TonKhos/{maKho}/{maLo}';
};

export type PutApiTonKhosByMaKhoByMaLoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTonKhosCheckData = {
    body?: CheckTonKhoRequest;
    path?: never;
    query?: never;
    url: '/api/TonKhos/check';
};

export type PostApiTonKhosCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTonKhosCheckallkhoData = {
    body?: CheckAllKhoRequest;
    path?: never;
    query?: never;
    url: '/api/TonKhos/checkallkho';
};

export type PostApiTonKhosCheckallkhoResponses = {
    /**
     * OK
     */
    200: unknown;
};
