"use client";
import { useState } from "react";
import Modal from "@/components/ui/Modal";
import SanPhamForm from "./SanPhamForm";
import { SanPhamWithPriceDTO } from "@/types";
import { Tag } from "lucide-react";

interface Props {
    onClose: () => void;
    onAdd: (data: SanPhamWithPriceDTO) => Promise<void> | void;
}

export default function AddSanPhamModal({ onClose, onAdd }: Props) {
    const [isSubmitting, setIsSubmitting] = useState(false);
    async function handleAdd(data: SanPhamWithPriceDTO) {
        try {
            setIsSubmitting(true);
            // Prepare the data
            const newData = {
                ...data,
                // Note: In a real app, ID and Date are usually generated by the Backend/Database
                MaSanPham: crypto.randomUUID(),
                MaSPCode: "SP_MOCK",
                NgayTao: new Date().toISOString(),
            };
            // Await the parent action (e.g., API call)
            await onAdd(newData);
            onClose();
        }
        catch (error) {
            console.error("Failed to add kho", error);
            // Optional: Set an error state here to show a message
        } finally {
            setIsSubmitting(false);
        }
    }

    return (
        <Modal size="lg">
            {/* Header Title */}
            <div className="flex items-center justify-center gap-3 mb-8">
                <Tag size={28} />
                <h2 className="text-2xl font-bold text-slate-900">Thêm sản phẩm</h2>
            </div>
            <SanPhamForm
                submitText={isSubmitting ? "Đang thêm..." : "Thêm sản phẩm"}
                onSubmit={handleAdd}
                onCancel={onClose}
                isLoading={isSubmitting}
            />
        </Modal>
    );
}
